title: Default

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            type: markdown
        
  - width: 1/3
    sections:
      files:
        type: files
        image:
          back: white